
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Stu
 */
public class AccountInfo extends javax.swing.JFrame {

    /**
     * Creates new form AccountInfo
     */
    Account account;
    UserFile userFile;
    Interface loginScreen;

    public AccountInfo(String username, String password, Interface loginScreen) {
        initComponents();
        
        this.loginScreen = loginScreen;

        userFile = new UserFile(username, password);
        try {
            userFile.readFromFile();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Could not read file", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            dispose();
        }
        account = new Account(userFile.getText());
        
        fieldHolder.setText(account.getHolder());
        comboType.setSelectedIndex(account.getType());
        fieldNumber.setText(account.getNumber() + "");
        fieldBranchName.setText(account.getBranchName());
        fieldBranchCode.setText(account.getBranchCode());
        fieldBankName.setText(account.getBankName());
        labelBalance.setText(account.displayBalance());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fieldHolder = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        fieldNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldBranchName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldBranchCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldBankName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        labelBalance = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account Info");

        jLabel2.setText("Holder");

        jLabel3.setText("Account type");

        comboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Basic", "Standard", "Premium" }));

        jLabel4.setText("Number");

        jLabel5.setText("Branch name");

        jLabel6.setText("Branch code");

        jLabel7.setText("Bank name");

        jLabel8.setText("Balance:");

        labelBalance.setText("R0.00");

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Deposit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Withdraw");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hacker_1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBalance)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fieldHolder)
                            .addComponent(fieldBranchName)
                            .addComponent(fieldNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBranchCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldBankName)
                            .addComponent(comboType, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldBranchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldBranchCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelBalance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String text = JOptionPane.showInputDialog(this, "Enter amount:", "Deposit", JOptionPane.INFORMATION_MESSAGE);
        if (text == null) {
            return;
        }

        if (text.length() < 1) {
            return;
        }

        if (Character.toUpperCase(text.charAt(0)) == 'R') {
            text = text.substring(1);
        }

        double amount = Double.parseDouble(text);

        if (amount < 0) {
            JOptionPane.showMessageDialog(this, "Amount cannot be negative", "Invalid amount", JOptionPane.ERROR_MESSAGE);
            return;
        }

        account.desposit(amount);
        labelBalance.setText(account.displayBalance());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String text = JOptionPane.showInputDialog(this, "Enter amount:", "Withdrawal", JOptionPane.INFORMATION_MESSAGE);
        if (text == null) {
            return;
        }

        if (text.length() < 1) {
            return;
        }

        if (Character.toUpperCase(text.charAt(0)) == 'R') {
            text = text.substring(1);
        }

        double amount = Double.parseDouble(text);

        if (amount < 0) {
            JOptionPane.showMessageDialog(this, "Amount cannot be negative", "Invalid amount", JOptionPane.ERROR_MESSAGE);
            return;
        }

        account.withdraw(amount);
        labelBalance.setText(account.displayBalance());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        account.setHolder(fieldHolder.getText());
        account.setType(comboType.getSelectedIndex());

        if (fieldNumber.getText().length() > 0) {
            account.setNumber(Integer.parseInt(fieldNumber.getText()));
        } else {
            account.setNumber(0);
        }
        account.setBranchName(fieldBranchName.getText());
        account.setBranchCode(fieldBranchCode.getText());
        account.setBankName(fieldBankName.getText());

        userFile.setText(account.forFile());

        try {
            userFile.writeToFile();
            dispose();
            loginScreen.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Could not apply changes", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboType;
    private javax.swing.JTextField fieldBankName;
    private javax.swing.JTextField fieldBranchCode;
    private javax.swing.JTextField fieldBranchName;
    private javax.swing.JTextField fieldHolder;
    private javax.swing.JTextField fieldNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBalance;
    // End of variables declaration//GEN-END:variables
}
